name: (Compiler) Publish Prereleases Weekly

on:
    # At 10 minutes past 9:00 on Mon

env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles

jobs:
  publish_prerelease_beta:
    name: Publish to beta channel
    uses: facebook/react/.github/workflows/compiler_prereleases.yml@main
    with:
      commit_sha: ${{ github.sha }}
      release_channel: beta
      dist_tag: beta
      version_name: '19.0.0'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
